CREATE TABLE IF NOT EXISTS archive(
    user_id serial PRIMARY KEY,
    form_id serial,
    form_status text NOT NULL,
    archive_status boolean NOT NULL,
    affiant_full_name text NOT NULL,
    other_names text,
    previous_name text,
    name_change_status boolean NOT NULL,
    reason_for_change text,
    social_security_num int NOT NULL,
    social_security_date date NOT NULL, 
    social_security_country text NOT NULL, 
    passport_number int NOT NULL, 
    passport_date date NOT NULL,
    passport_country text NOT NULL, 
    NHI_number int NOT NULL, 
    NHI_date date NOT NULL,
    NHI_country text NOT NULL, 
    dob date NOT NULL,
    place_of_birth text NOT NULL,
    nationality text NOT NULL,
    acquired_nationality text,
    spouse_name text,
    affiants_address text NOT NULL, 
    residencial_phone_number int NOT NULL, 
    residenceial_fax_num int, 
    residencial_email text,
    created_on TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);